#!/usr/bin/env bash
# numpy lib descriptor for build-wheel.sh
# Meson C++ build with WASM C++ exceptions (PIC+EH libc++ link tier).
# De-localized from build-numpy2-eh.sh; paths updated to image layout
# (/opt/toolchain/... instead of $CLAUDE_JOB_DIR/tmp/...).
# Sourced by build-wheel.sh (venv active; $SRC, $CROSS, $LIBCXX available).

LIB_VERSION="2.5.0"
BUILD_DEPS=("meson-python>=0.15" "Cython>=3.0.6" "ninja")

# WASM C++ exceptions + emscripten compat defines required by numpy
EXTRA_CFLAGS="-fwasm-exceptions -mllvm -wasm-use-legacy-eh=false -D__EMSCRIPTEN__=1 -DNPY_NO_SIGNAL"

# -nostdlib++: suppress clang's automatic libc++ link so LDWRAP can append
# the correct PIC+EH libc++ archives (avoids double-linking or wrong tier).
EXTRA_LDFLAGS="-nostdlib++"

# Meson cross file generated by pre_build_hook (fixed path, reused by pandas)
_NUMPY_CROSSFILE=/tmp/wasi-eh-numpy.cross

# Pass meson setup args to python -m build
BUILD_CMD_EXTRA_ARGS=(
  -Cbuild-dir=build
  "-Csetup-args=--cross-file=$_NUMPY_CROSSFILE"
  "-Csetup-args=-Dblas=none"
  "-Csetup-args=-Dlapack=none"
  "-Csetup-args=-Dallow-noblas=true"
  "-Csetup-args=-Ddisable-optimization=true"
)

fetch_source() {
  # pip download --no-binary triggers meson metadata prep which needs host Python
  # dev headers (not present in the toolchain image). Use PyPI JSON API instead.
  python - "${LIB_VERSION}" "$SRC" <<'PY'
import json, shutil, sys, urllib.request
ver, out_dir = sys.argv[1], sys.argv[2]
data = json.load(urllib.request.urlopen(f"https://pypi.org/pypi/numpy/{ver}/json"))
url = next(u["url"] for u in data["urls"] if u["packagetype"] == "sdist")
out = f"{out_dir}/numpy-{ver}.tar.gz"
print(f"Downloading {url}", flush=True)
with urllib.request.urlopen(url) as r, open(out, "wb") as f:
    shutil.copyfileobj(r, f)
PY
  tar xf "$SRC/numpy-${LIB_VERSION}.tar.gz" -C "$SRC" --strip-components=1
}

# Called by build-wheel.sh after cross env is set, cwd = $SRC.
pre_build_hook() {
  # ── Install patchelf (numpy's build-system.requires; host-only tool) ─────
  # pip install is confused by _PYTHON_HOST_PLATFORM=wasi-0.0.0-wasm32 (set by
  # build-wheel.sh) and tries to build patchelf for WASI. Run in a subshell
  # with cleared platform env vars so pip downloads the x86_64 prebuilt wheel.
  (
    unset _PYTHON_HOST_PLATFORM _PYTHON_SYSCONFIGDATA_NAME
    python -m pip install -q "patchelf>=0.11.0"
  )

  local SDK=/opt/wasi-sdk
  local L="$LIBCXX"   # /opt/toolchain/build-cxx/lib
  local RT="$SDK/lib/clang/22/lib/wasm32-unknown-wasip2/libclang_rt.builtins.a"
  local TARGET=wasm32-wasip2

  # ── Meson cross file ──────────────────────────────────────────────────────
  cat > "$_NUMPY_CROSSFILE" <<EOF
[binaries]
c = ['$SDK/bin/clang', '--target=$TARGET', '-mcpu=lime1']
cpp = ['$SDK/bin/clang++', '--target=$TARGET', '-mcpu=lime1']
ar = '$SDK/bin/llvm-ar'
ranlib = '$SDK/bin/llvm-ranlib'
pkgconfig = 'pkg-config'
[properties]
needs_exe_wrapper = true
skip_sanity_check = true
longdouble_format = 'IEEE_QUAD_LE'
[host_machine]
system = 'emscripten'
cpu_family = 'wasm32'
cpu = 'wasm'
endian = 'little'
EOF

  # ── Replace generic LDWRAP with PIC+EH version ────────────────────────────
  # The generic wrapper only strips host lib refs; this one additionally appends
  # the PIC+EH libc++/libc++abi/libunwind archives + compiler-rt builtins so
  # wasm-ld resolves C++ exception symbols without the sysroot's non-PIC libc++.
  cat > "$LDWRAP" <<WRAP
#!/usr/bin/env bash
out=()
for a in "\$@"; do
  case "\$a" in
    --start-group|--end-group|/usr/lib/*|/lib/*|-L/usr/lib*|-L/lib/*) ;;
    *) out+=("\$a");;
  esac
done
exec "$SDK/bin/wasm-ld" "\${out[@]}" \
  "$L/libc++.a" "$L/libc++abi.a" "$L/libunwind.a" \
  "$RT" --allow-undefined
WRAP
  chmod +x "$LDWRAP"

  # meson reads CC_LD/CXX_LD and translates to -fuse-ld=<LDWRAP> for the compiler
  export CC_LD="$LDWRAP"
  export CXX_LD="$LDWRAP"

  # ── Source patch: dladdr/backtrace are absent on WASI ─────────────────────
  sed -i \
    's/#if defined HAVE_BACKTRACE && defined HAVE_DLFCN_H$/#if defined HAVE_BACKTRACE \&\& defined HAVE_DLFCN_H \&\& !defined(__wasi__) \&\& !defined(__EMSCRIPTEN__)/' \
    numpy/_core/src/multiarray/temp_elide.c || true
}
